POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "crg1@domain.com",
  "password": "abc123def456",
  "isOwner": false
}

###
##
##
POST http://localhost:8080/api/v1/auth/verification-code
Content-Type: application/json

{
    "cookie": "555e3cfc-5989-4657-a0e9-2b56397ea849",
    "code": 6003
}

###

POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "email": "crg1@domain.com",
  "password": "abc123def456"
}

# {
#   "email": "mail12@domain.com",
#   "password": "abc123def456"
# }






### create a new dog
POST http://localhost:8080/api/v1/dogs
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLciOJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODc1ODU0NCwidXNlcklkIjozNH0.a7pzGG3UCRU0SKd9C7_Ku0flfsReqLyyEnWISdULVnc

{
  "userId": 34,
  "name": "dog1",
  "breed": 55,
  "size": 1,
  "birthDate": "2020-11-17T23:23:23+0000",
  "isMale": true,
  "isSterilized": false,
  "notes": "test 1"
}

###

GET http://localhost:8080/api/v1/dogs
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgxMDgwNCwidXNlcklkIjozNH0.zKUF1pHyv11dYuTZ2MoQlXa9veZNNCGJLz2mIpDnITc


### get all breeds
GET http://localhost:8080/api/v1/catalogs/breeds
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODc2MTMxNSwidXNlcklkIjozNH0.zv6Jt2GcQJIVhT9gOP9rey8o0BuyWj50Go6DdrsxECQ

### get all countries
GET http://localhost:8080/api/v1/catalogs/countries
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgzMTM0MSwidXNlcklkIjozNH0.mUa38CG29c8Asj3TwnydE9x8z3vZrSHt7ItoLE0S3dU

### get all cities
GET http://localhost:8080/api/v1/catalogs/countries/332/cities
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgzMTM0MSwidXNlcklkIjozNH0.mUa38CG29c8Asj3TwnydE9x8z3vZrSHt7ItoLE0S3dU

###

POST http://localhost:8080/api/v1/payment-methods
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgxMDgwNCwidXNlcklkIjozNH0.zKUF1pHyv11dYuTZ2MoQlXa9veZNNCGJLz2mIpDnITc
Content-Type: application/json

{
    "name": "test payment method",
    "numbers": "1234567812345678",
    "expirationDate": "2022-11-01T00:00:00+0000"
}

###
GET http://localhost:8080/api/v1/payment-methods
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgxMDgwNCwidXNlcklkIjozNH0.zKUF1pHyv11dYuTZ2MoQlXa9veZNNCGJLz2mIpDnITc

### create a new dog
POST http://localhost:8080/api/v1/users/address
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsInJvbGVzIjpbIkdFVF9ET0dTIiwiQUREX0RPRyIsIlNFQVJDSF9CT0FSRElORyIsIkJPT0tfQk9BUkRJTkciLCJTRUFSQ0hfV0FMS0lORyIsIkJPT0tfV0FMS0lORyIsIlNFQVJDSF9UUkFJTklORyIsIkJPT0tfVFJBSU5JTkciLCJTRUFSQ0hfTlVSU0lORyIsIkJPT0tfTlVSU0lORyIsIkdFVF9QUk9GSUxFIiwiR0VUX1JFVklFV1MiLCJHRVRfSU5TVVJBTkNFX1BMQU5TIiwiQlVZX0lOU1VSQU5DRSIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQUREX1BBWU1FTlRfTUVUSE9EIiwiR0VUX09XTkVSX0JPT0tJTkdTIiwiR0VUX0RPR19CWV9JRCIsIlNFTkRfTUVTU0FHRSIsIlVQREFURV9QUk9GSUxFIiwiR0VUX0JSRUVEUyIsIkdFVF9DT1VOVFJJRVMiLCJHRVRfQ0lUSUVTIl0sImlzcyI6ImZpZWxhbWlnbyIsImV4cCI6MTY2ODgzMTM0MSwidXNlcklkIjozNH0.mUa38CG29c8Asj3TwnydE9x8z3vZrSHt7ItoLE0S3dU

{
  "address1": "test address 1",
  "address2": "test address 2",
  "cityId": 333,
  "countryId": 332,
  "zone": "test zone"
}

### upload user details
POST http://localhost:8080/api/v1/caregivers/bio-details
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3NyIsImlzT3duZXIiOmZhbHNlLCJyb2xlcyI6WyJHRVRfQ0lUSUVTIiwiR0VUX0NPVU5UUklFUyIsIlVQREFURV9QUk9GSUxFIiwiU0VORF9NRVNTQUdFIiwiRklOSVNIX0JPT0tJTkciLCJHRVRfRE9HX0JZX0lEIiwiUkVKRUNUX0JPT0tJTkciLCJDT05GSVJNX0JPT0tJTkciLCJHRVRfQ0FSRUdJVkVSX0JPT0tJTkdTIiwiQUREX0hPVVNFX0RFVEFJTFMiLCJBRERfRVhQRVJJRU5DRSIsIlVQREFURV9OVVJTSU5HIiwiVVBEQVRFX1dBTEtJTkciLCJVUERBVEVfVFJBSU5JTkciLCJVUERBVEVfQk9BUkRJTkciLCJDUkVBVEVfTlVSU0lORyIsIkNSRUFURV9XQUxLSU5HIiwiQ1JFQVRFX1RSQUlOSU5HIiwiQ1JFQVRFX0JPQVJESU5HIiwiVVBEQVRFX0JPT0tJTkciLCJDQU5DRUxfQk9PS0lORyIsIkdFVF9SRVZJRVdTIiwiR0VUX1BST0ZJTEUiLCJHRVRfRE9HUyJdLCJpc3MiOiJmaWVsYW1pZ28iLCJjYXJlZ2l2ZXJJZCI6OSwiZXhwIjoxNjY5MzE0OTY2LCJ1c2VySWQiOjc3fQ.la2VpgCSbmrUOCF7EbyWIvzO-QqCZ1psMCbeGzUaxng

{
    "bio":"Biografiatttt",
    "experience":[
      "tengo hambre",
      "tengo sueño"
    ],
    "houseFeatures":["Es chiquita"]
}



### get all caregiver pictures
GET http://localhost:8080/api/v1/caregivers/9/pictures
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNCIsImZpcnN0TmFtZSI6Ik1vYmlsZSB0ZXN0IDIiLCJsYXN0TmFtZSI6InRlc3RldCIsImlzT3duZXIiOnRydWUsInJvbGVzIjpbIkdFVF9DSVRJRVMiLCJHRVRfQ09VTlRSSUVTIiwiR0VUX0JSRUVEUyIsIlVQREFURV9QUk9GSUxFIiwiU0VORF9NRVNTQUdFIiwiR0VUX0RPR19CWV9JRCIsIkdFVF9PV05FUl9CT09LSU5HUyIsIkFERF9QQVlNRU5UX01FVEhPRCIsIlZJRVdfVkVURVJJTkFSSUVTIiwiQlVZX0lOU1VSQU5DRSIsIkdFVF9JTlNVUkFOQ0VfUExBTlMiLCJHRVRfUkVWSUVXUyIsIkdFVF9QUk9GSUxFIiwiQk9PS19OVVJTSU5HIiwiU0VBUkNIX05VUlNJTkciLCJCT09LX1RSQUlOSU5HIiwiU0VBUkNIX1RSQUlOSU5HIiwiQk9PS19XQUxLSU5HIiwiU0VBUkNIX1dBTEtJTkciLCJCT09LX0JPQVJESU5HIiwiU0VBUkNIX0JPQVJESU5HIiwiQUREX0RPRyIsIkdFVF9ET0dTIl0sImlzcyI6ImZpZWxhbWlnbyIsImNhcmVnaXZlcklkIjotMSwiZXhwIjoxNjY5MjQyMzk0LCJ1c2VySWQiOjM0fQ.OwpMJOUGlELNcXVgjvgOFH6fPyxtxpHm5uJh7YxfmgQ

