POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "mail@domain.com",
  "password": "abc123def456",
  "isOwner": "true"
}

###
##
##
POST http://localhost:8080/api/v1/auth/verification-code
Content-Type: application/json

{
    "cookie": "c009bd2f-4ef7-41b5-b830-d869b99b260a",
    "code": 3758
}